In [11]:
import numpy as np
import pandas as pd

In [12]:
df= pd.read_csv('F://melbourne.csv')

In [13]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,04-03-2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,04-06-2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
7,Abbotsford,16 Maugie St,4,h,NaN,SN,Nelson,06-08-2016,2.5,3067.0,...,2.0,2.0,400.0,220.0,2006.0,Yarra,-37.79650,144.99650,Northern Metropolitan,4019.0
8,Abbotsford,53 Turner St,2,h,NaN,S,Biggin,06-08-2016,2.5,3067.0,...,1.0,2.0,201.0,NaN,1900.0,Yarra,-37.79950,144.99740,Northern Metropolitan,4019.0
9,Abbotsford,99 Turner St,2,h,NaN,S,Collins,06-08-2016,2.5,3067.0,...,2.0,1.0,202.0,NaN,1900.0,Yarra,-37.79960,144.99890,Northern Metropolitan,4019.0
10,Abbotsford,129 Charles St,2,h,941000.0,S,Jellis,07-05-2016,2.5,3067.0,...,1.0,0.0,181.0,NaN,NaN,Yarra,-37.80410,144.99530,Northern Metropolitan,4019.0
11,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,07-05-2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.80240,144.99930,Northern Metropolitan,4019.0
12,Abbotsford,121/56 Nicholson St,2,u,NaN,PI,Biggin,07-11-2016,2.5,3067.0,...,2.0,1.0,4292.0,82.0,2009.0,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
13,Abbotsford,17 Raphael St,4,h,NaN,W,Biggin,07-11-2016,2.5,3067.0,...,2.0,0.0,230.0,147.0,1860.0,Yarra,-37.80660,144.99360,Northern Metropolitan,4019.0
14,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,08-10-2016,2.5,3067.0,...,1.0,2.0,256.0,107.0,1890.0,Yarra,-37.80600,144.99540,Northern Metropolitan,4019.0
15,Abbotsford,217 Langridge St,3,h,1000000.0,S,Jellis,08-10-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
16,Abbotsford,18a Mollison St,2,t,745000.0,S,Jellis,08-10-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
17,Abbotsford,6/241 Nicholson St,1,u,300000.0,S,Biggin,08-10-2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80080,144.99730,Northern Metropolitan,4019.0
18,Abbotsford,10 Valiant St,2,h,1097000.0,S,Biggin,08-10-2016,2.5,3067.0,...,1.0,2.0,220.0,75.0,1900.0,Yarra,-37.80100,144.99890,Northern Metropolitan,4019.0
19,Abbotsford,403/609 Victoria St,2,u,542000.0,S,Dingle,08-10-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
20,Abbotsford,2 Rich St,2,h,NaN,SP,Biggin,10-12-2016,2.5,3067.0,...,1.0,1.0,176.0,80.0,1925.0,Yarra,-37.79980,144.99720,Northern Metropolitan,4019.0
21,Abbotsford,25/84 Trenerry Cr,2,u,760000.0,SP,Biggin,10-12-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
22,Abbotsford,106/119 Turner St,1,u,481000.0,SP,Purplebricks,10-12-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
23,Abbotsford,411/8 Grosvenor St,2,u,700000.0,VB,Jellis,12-11-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.81100,145.00670,Northern Metropolitan,4019.0
24,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12-11-2016,2.5,3067.0,...,2.0,2.0,214.0,190.0,2005.0,Yarra,-37.80850,144.99640,Northern Metropolitan,4019.0
25,Abbotsford,123/56 Nicholson St,2,u,750000.0,S,Biggin,12-11-2016,2.5,3067.0,...,2.0,1.0,0.0,94.0,2009.0,Yarra,-37.80780,144.99650,Northern Metropolitan,4019.0
26,Abbotsford,22 Park St,4,h,1985000.0,S,Biggin,12-11-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-37.80840,144.99420,Northern Metropolitan,4019.0
27,Abbotsford,13/84 Trenerry Cr,1,u,500000.0,S,Biggin,12-11-2016,2.5,3067.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
28,Abbotsford,45 William St,2,h,1172500.0,S,Biggin,13-08-2016,2.5,3067.0,...,1.0,1.0,195.0,NaN,NaN,Yarra,-37.80840,144.99730,Northern Metropolitan,4019.0
29,Abbotsford,7/20 Abbotsford St,1,u,441000.0,SP,Greg,14-05-2016,2.5,3067.0,...,1.0,1.0,0.0,NaN,NaN,Yarra,-37.80160,144.99880,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23517,Vermont South,2 Settlers Ct,4,h,1295000.0,SP,Purplebricks,26-08-2017,17.2,3133.0,...,2.0,2.0,NaN,190.0,1980.0,NaN,-37.85928,145.18715,Eastern Metropolitan,4280.0
23518,Vermont South,9 Winswood Cl,4,h,1250000.0,PI,Philip,26-08-2017,17.2,3133.0,...,2.0,2.0,986.0,NaN,NaN,NaN,-37.84679,145.20051,Eastern Metropolitan,4280.0
23519,Viewbank,149 Graham Rd,5,h,1316000.0,SP,Nelson,26-08-2017,8.9,3084.0,...,3.0,3.0,696.0,NaN,NaN,NaN,-37.73501,145.08341,Eastern Metropolitan,2698.0
23520,Viewbank,7 Northwood Dr,4,h,NaN,SP,Nelson,26-08-2017,8.9,3084.0,...,2.0,2.0,1105.0,237.0,1980.0,NaN,-37.73703,145.09392,Eastern Metropolitan,2698.0
23521,Wantirna,16 chesterfield Ct,4,h,951000.0,S,Ray,26-08-2017,14.7,3152.0,...,2.0,2.0,704.0,200.0,1981.0,NaN,-37.85639,145.23536,Eastern Metropolitan,5424.0
23522,Wantirna,9 eton Sq,4,h,NaN,PI,Ray,26-08-2017,14.7,3152.0,...,2.0,3.0,785.0,NaN,NaN,NaN,-37.85297,145.23815,Eastern Metropolitan,5424.0
23523,Wantirna South,12 Armagh Cr,4,h,1323000.0,S,Barry,26-08-2017,14.7,3152.0,...,2.0,2.0,551.0,NaN,NaN,NaN,-37.87608,145.22390,Eastern Metropolitan,7082.0
23524,Wantirna South,34 Fewster Dr,3,h,970000.0,S,Barry,26-08-2017,14.7,3152.0,...,2.0,2.0,674.0,NaN,NaN,NaN,-37.88360,145.22805,Eastern Metropolitan,7082.0
23525,Wantirna South,15 Mara Cl,4,h,1330000.0,S,Barry,26-08-2017,14.7,3152.0,...,2.0,2.0,717.0,191.0,1980.0,NaN,-37.86887,145.22116,Eastern Metropolitan,7082.0
23526,Watsonia,2/14 Daours Ct,2,u,590000.0,S,Lindellas,26-08-2017,14.5,3087.0,...,1.0,1.0,NaN,83.0,2010.0,NaN,-37.71500,145.07649,Northern Metropolitan,2329.0
23527,Watsonia,76 Kenmare St,2,h,650000.0,PI,Morrison,26-08-2017,14.5,3087.0,...,1.0,1.0,210.0,79.0,2006.0,NaN,-37.70657,145.07878,Northern Metropolitan,2329.0
23528,Watsonia North,22 Meakin St,3,h,NaN,PI,Nelson,26-08-2017,14.5,3087.0,...,2.0,3.0,NaN,NaN,NaN,NaN,-37.70186,145.08635,Northern Metropolitan,1442.0
23529,Werribee,6 Feijoa Ct,5,h,NaN,W,YPA,26-08-2017,14.7,3030.0,...,3.0,2.0,535.0,NaN,NaN,NaN,-37.89362,144.66767,Western Metropolitan,16166.0
23530,Werribee,11 Gundaroo Sq,4,h,NaN,PI,Stockdale,26-08-2017,14.7,3030.0,...,2.0,6.0,NaN,NaN,NaN,NaN,-37.91230,144.66980,Western Metropolitan,16166.0
23531,Werribee,91 Latham St,4,h,540000.0,PI,Triwest,26-08-2017,14.7,3030.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,16166.0
23532,Werribee,5 Nuragi Ct,4,h,635000.0,S,hockingstuart,26-08-2017,14.7,3030.0,...,2.0,1.0,662.0,172.0,1980.0,NaN,-37.89327,144.64789,Western Metropolitan,16166.0
23533,Werribee,3 Sky Ct,3,h,NaN,PI,Barry,26-08-2017,14.7,3030.0,...,2.0,2.0,NaN,NaN,NaN,NaN,-37.89096,144.64200,Western Metropolitan,16166.0
23534,West Footscray,1/21 Waratah St,2,t,655000.0,S,Jas,26-08-2017,6.4,3012.0,...,2.0,1.0,NaN,135.0,2012.0,NaN,-37.80968,144.86819,Western Metropolitan,5058.0
23535,Westmeadows,9 Black St,3,h,582000.0,S,Red,26-08-2017,16.5,3049.0,...,2.0,2.0,256.0,NaN,NaN,NaN,-37.67917,144.89390,Northern Metropolitan,2474.0
23536,Westmeadows,81 Hillcrest Dr,4,h,720000.0,VB,Barry,26-08-2017,16.5,3049.0,...,2.0,0.0,NaN,NaN,NaN,NaN,-37.68006,144.87550,Northern Metropolitan,2474.0
23537,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26-08-2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
23538,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26-08-2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
23539,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26-08-2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26-08-2017,6.8,3016.0,...,2.0,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0
23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26-08-2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
23542,Wyndham Vale,25 Clitheroe Dr,3,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,...,1.0,0.0,552.0,119.0,1990.0,NaN,-37.90032,144.61839,Western Metropolitan,5262.0
23543,Wyndham Vale,19 Dalrymple Bvd,4,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [14]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0

In [15]:
df.tail()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
23542,Wyndham Vale,25 Clitheroe Dr,3,u,NaN,PN,Harcourts,26-08-2017,27.2,3024.0,...,1.0,0.0,552.0,119.0,1990.0,NaN,-37.90032,144.61839,Western Metropolitan,5262.0
23543,Wyndham Vale,19 Dalrymple Bvd,4,h,NaN,S,hockingstuart,26-08-2017,27.2,3024.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-37.87882,144.60184,Western Metropolitan,5262.0
23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26-08-2017,12.7,3085.0,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26-08-2017,6.3,3013.0,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [16]:
df.shape

(23547, 21)

In [17]:
df.keys()

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [18]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [19]:
#indexing and slicing

In [20]:
df[0,0]

KeyError: (0, 0)

In [21]:
df.iloc[0]

Suburb                      Abbotsford
Address                  68 Studley St
Rooms                                2
Type                                 h
Price                              NaN
Method                              SS
SellerG                         Jellis
Date                        03-09-2016
Distance                           2.5
Postcode                          3067
Bedroom2                             2
Bathroom                             1
Car                                  1
Landsize                           126
BuildingArea                       NaN
YearBuilt                          NaN
CouncilArea                      Yarra
Lattitude                     -37.8014
Longtitude                     144.996
Regionname       Northern Metropolitan
Propertycount                     4019
Name: 0, dtype: object

In [22]:
df.iloc[0:5]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0

In [23]:
df.iloc[:,'Rooms']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [24]:
df.loc[:,'Rooms']

0        2
1        2
2        2
3        3
4        3
5        3
6        4
7        4
8        2
9        2
10       2
11       3
12       2
13       4
14       2
15       3
16       2
17       1
18       2
19       2
20       2
21       2
22       1
23       2
24       3
25       2
26       4
27       1
28       2
29       1
        ..
23517    4
23518    4
23519    5
23520    4
23521    4
23522    4
23523    4
23524    3
23525    4
23526    2
23527    2
23528    3
23529    5
23530    4
23531    4
23532    4
23533    3
23534    2
23535    3
23536    4
23537    4
23538    3
23539    3
23540    2
23541    4
23542    3
23543    4
23544    4
23545    4
23546    4
Name: Rooms, Length: 23547, dtype: int64

In [25]:
df.info()
#here in price---> it has  18396, it means there around 5k missing data..etc..

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23547 entries, 0 to 23546
Data columns (total 21 columns):
Suburb           23547 non-null object
Address          23547 non-null object
Rooms            23547 non-null int64
Type             23547 non-null object
Price            18396 non-null float64
Method           23547 non-null object
SellerG          23547 non-null object
Date             23547 non-null object
Distance         23546 non-null float64
Postcode         23546 non-null float64
Bedroom2         19066 non-null float64
Bathroom         19063 non-null float64
Car              18921 non-null float64
Landsize         17410 non-null float64
BuildingArea     10018 non-null float64
YearBuilt        11540 non-null float64
CouncilArea      15656 non-null object
Lattitude        19243 non-null float64
Longtitude       19243 non-null float64
Regionname       23546 non-null object
Propertycount    23546 non-null float64
dtypes: float64(12), int64(1), object(8)
memory usage: 3.8+ MB

In [26]:
#indentifying the missing values

In [27]:
df.isnull()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
9,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
16,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
20,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
22,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23517,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
23518,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23519,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23520,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23521,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23522,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23523,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23524,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23525,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23526,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
23527,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23528,False,False,False,False,True,False,False,False,False,False,...,False,False,True,True,True,True,False,False,False,False
23529,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23530,False,False,False,False,True,False,False,False,False,False,...,False,False,True,True,True,True,False,False,False,False
23531,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False
23532,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23533,False,False,False,False,True,False,False,False,False,False,...,False,False,True,True,True,True,False,False,False,False
23534,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
23535,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,False,False,False,False
23536,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,False,False,False,False
23537,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
23538,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23539,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
23540,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False
23541,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23542,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23543,False,False,False,False,True,False,False,False,False,False,...,True,True,True,True,True,True,False,False,False,False
23544,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,False,False,False,False
23545,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
23546,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,False

In [28]:
#summing up the missing values (col-wise)
df.isnull().sum()
#in each column how many missing data is there inn col wise

Suburb               0
Address              0
Rooms                0
Type                 0
Price             5151
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          4481
Bathroom          4484
Car               4626
Landsize          6137
BuildingArea     13529
YearBuilt        12007
CouncilArea       7891
Lattitude         4304
Longtitude        4304
Regionname           1
Propertycount        1
dtype: int64

In [29]:
#col having at least one missing value
df.isnull().any()

Suburb           False
Address          False
Rooms            False
Type             False
Price             True
Method           False
SellerG          False
Date             False
Distance          True
Postcode          True
Bedroom2          True
Bathroom          True
Car               True
Landsize          True
BuildingArea      True
YearBuilt         True
CouncilArea       True
Lattitude         True
Longtitude        True
Regionname        True
Propertycount     True
dtype: bool

In [30]:
#above is equivalent to axis=0(by default, any()--> operators on col)
df.isnull().any(axis=0)
#this is finding missing value in col-wise--->coz axis=0

Suburb           False
Address          False
Rooms            False
Type             False
Price             True
Method           False
SellerG          False
Date             False
Distance          True
Postcode          True
Bedroom2          True
Bathroom          True
Car               True
Landsize          True
BuildingArea      True
YearBuilt         True
CouncilArea       True
Lattitude         True
Longtitude        True
Regionname        True
Propertycount     True
dtype: bool

In [31]:
df.isnull().any(axis=1)
#this is finding missing value in row-wise--->coz axis=1

0         True
1         True
2        False
3         True
4        False
5         True
6        False
7         True
8         True
9         True
10        True
11       False
12        True
13        True
14       False
15        True
16        True
17        True
18       False
19        True
20        True
21        True
22        True
23        True
24       False
25       False
26        True
27        True
28        True
29        True
         ...
23517     True
23518     True
23519     True
23520     True
23521     True
23522     True
23523     True
23524     True
23525     True
23526     True
23527     True
23528     True
23529     True
23530     True
23531     True
23532     True
23533     True
23534     True
23535     True
23536     True
23537     True
23538     True
23539     True
23540     True
23541     True
23542     True
23543     True
23544     True
23545     True
23546     True
Length: 23547, dtype: bool

In [32]:
df.isnull().all(axis=1)
#this is to find all the missing values in a row

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
23517    False
23518    False
23519    False
23520    False
23521    False
23522    False
23523    False
23524    False
23525    False
23526    False
23527    False
23528    False
23529    False
23530    False
23531    False
23532    False
23533    False
23534    False
23535    False
23536    False
23537    False
23538    False
23539    False
23540    False
23541    False
23542    False
23543    False
23544    False
23545    False
23546    False
Length: 23547, dtype: bool

In [33]:
df.isnull().all(axis=1).sum()

0

In [34]:
df.isnull().sum(axis=1)
#sum of missing values in each row

0        3
1        2
2        0
3        3
4        0
5        2
6        0
7        1
8        2
9        2
10       2
11       0
12       1
13       1
14       0
15       9
16       9
17       2
18       0
19       9
20       1
21       9
22       9
23       2
24       0
25       0
26       7
27       9
28       2
29       2
        ..
23517    2
23518    3
23519    3
23520    2
23521    1
23522    4
23523    3
23524    3
23525    1
23526    2
23527    1
23528    5
23529    4
23530    5
23531    9
23532    1
23533    5
23534    2
23535    3
23536    4
23537    2
23538    1
23539    2
23540    2
23541    1
23542    2
23543    8
23544    4
23545    1
23546    2
Length: 23547, dtype: int64

### treating missing values:
- there are two wasy to treat missing values
1. delete: Delete missing values
2. impute:
    - Imputing by a simple satistic: Replace the missing values by another value, commonly the mean, median, mode
    - Predictive techniques: Use statistical models such as K-NN, SVM etc., to predict and impute missing values.
- In generally, Imputation makes assumption about the missing values and replace missing values by arbitary numbers such as mean, median, mode etc,.. it should be used only when you are reasonably confident about the assumptions
- Otherwise, deletion is often safes and recommended. You may lose some data, but will not make any unreasonable assumptions.

Cautions: Always have a backup of the original data if you're deleting missing values

In [35]:
#to know the percentage of missing values in (col-wise)
round(100*(df.isnull().sum()/len(df.index)),2)  #-----> 2--> is decimals

Suburb            0.00
Address           0.00
Rooms             0.00
Type              0.00
Price            21.88
Method            0.00
SellerG           0.00
Date              0.00
Distance          0.00
Postcode          0.00
Bedroom2         19.03
Bathroom         19.04
Car              19.65
Landsize         26.06
BuildingArea     57.46
YearBuilt        50.99
CouncilArea      33.51
Lattitude        18.28
Longtitude       18.28
Regionname        0.00
Propertycount     0.00
dtype: float64

In [36]:
#removing three cols
df=df.drop('BuildingArea',axis=1)
df=df.drop('YearBuilt',axis=1)
df=df.drop('CouncilArea',axis=1)

round(100*(df.isnull().sum()/len(df.index)),2)
######## This type of code should be only one time execution

# if any error do seperate

Suburb            0.00
Address           0.00
Rooms             0.00
Type              0.00
Price            21.88
Method            0.00
SellerG           0.00
Date              0.00
Distance          0.00
Postcode          0.00
Bedroom2         19.03
Bathroom         19.04
Car              19.65
Landsize         26.06
Lattitude        18.28
Longtitude       18.28
Regionname        0.00
Propertycount     0.00
dtype: float64

In [37]:
df=df.drop('CouncilArea',axis=1)
round(100*(df.isnull().sum()/len(df.index)),2)

KeyError: "['CouncilArea'] not found in axis"

In [38]:
df[df.isnull().sum(axis=1)>5]

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Regionname,Propertycount
15,Abbotsford,217 Langridge St,3,h,1000000.0,S,Jellis,08-10-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
16,Abbotsford,18a Mollison St,2,t,745000.0,S,Jellis,08-10-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
19,Abbotsford,403/609 Victoria St,2,u,542000.0,S,Dingle,08-10-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
21,Abbotsford,25/84 Trenerry Cr,2,u,760000.0,SP,Biggin,10-12-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
22,Abbotsford,106/119 Turner St,1,u,481000.0,SP,Purplebricks,10-12-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
27,Abbotsford,13/84 Trenerry Cr,1,u,500000.0,S,Biggin,12-11-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
33,Abbotsford,250 Langridge St,2,t,847000.0,S,Jellis,16-07-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
34,Abbotsford,16b Mollison St,2,h,NaN,PI,Biggin,16-07-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
45,Abbotsford,65/80 Trenerry Cr,1,u,480000.0,S,Biggin,19-11-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
46,Abbotsford,119/52 Nicholson St,1,u,423500.0,S,hockingstuart,22-05-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
52,Abbotsford,49/84 Trenerry Cr,2,h,700000.0,S,Biggin,23-04-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
60,Abbotsford,4/328 Johnston St,2,u,NaN,PI,Biggin,28-05-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
62,Abbotsford,82/84 Trenerry Cr,2,u,970000.0,SP,Biggin,28-05-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
65,Abbotsford,40/80 Trenerry Cr,3,h,927000.0,S,Biggin,30-07-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
74,Airport West,4/9 West Ct,2,t,420000.0,VB,Barry,04-06-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
75,Airport West,1/36 York St,3,t,500000.0,VB,Nelson,04-06-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
76,Airport West,33 Bowes Av,5,h,1035000.0,S,Airport,06-08-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
77,Airport West,89 Bowes Av,4,h,960000.0,S,Barry,06-08-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
78,Airport West,45 Laurence Av,4,h,960000.0,S,Nelson,06-08-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
84,Airport West,81a Roberts Rd,3,h,680000.0,VB,Nelson,08-10-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
87,Airport West,3/24 Elstone Av,3,u,600000.0,VB,Nelson,10-09-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
89,Airport West,37a North St,3,t,760000.0,PI,Barry,10-12-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
91,Airport West,1/69 Bowes Av,3,u,580000.0,VB,Nelson,12-11-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
92,Airport West,2/9 El Reno Cr,3,h,725000.0,PI,Ray,12-11-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
93,Airport West,92 McNamara Av,4,h,758000.0,S,Jellis,13-08-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
95,Airport West,20 Creswell Av,3,h,970000.0,S,Barry,14-05-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
97,Airport West,71 Bowes Av,4,h,985000.0,S,Barry,15-10-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
99,Airport West,2/112 Parer Rd,2,u,509500.0,SP,Nelson,15-10-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
107,Airport West,7 McNamara Av,3,h,715000.0,S,Barry,17-09-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
111,Airport West,1/41 Hillside Gr,2,t,460000.0,VB,Nelson,18-06-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23270,MacLeod,4 Tucker Wy,4,h,831000.0,S,Ray,26-08-2017,12.7,3085.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4168.0
23271,Maidstone,88a Ballarat Rd,3,t,706000.0,S,Sweeney,26-08-2017,6.4,3012.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3873.0
23290,Meadow Heights,22 Lightwood Cr,5,h,710000.0,S,YPA,26-08-2017,17.4,3048.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4704.0
23291,Melbourne,505/1 Roy St,2,u,NaN,SP,Kay,26-08-2017,0.0,3000.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,17496.0
23292,Melbourne,505/1 Roy St,2,u,NaN,S,Kay,26-08-2017,0.0,3000.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,17496.0
23300,Mentone,20A Winsome St,3,t,905000.0,S,Hodges,26-08-2017,20.0,3194.0,NaN,NaN,NaN,NaN,NaN,NaN,South-Eastern Metropolitan,6162.0
23302,Mickleham,3 Selkirk Wy,2,h,335000.0,S,YPA,26-08-2017,20.6,3064.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,1158.0
23318,Moonee Ponds,55 Pattison St,2,h,700000.0,VB,Nelson,26-08-2017,6.2,3039.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,6232.0
23333,Mount Waverley,19 Larch Cr,3,h,NaN,SN,Harcourts,26-08-2017,14.2,3149.0,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Metropolitan,13366.0
23337,Mulgrave,45 Carson St,3,t,826000.0,S,Win,26-08-2017,18.8,3170.0,NaN,NaN,NaN,NaN,NaN,NaN,South-Eastern Metropolitan,7113.0
23352,Northcote,2/241 Heidelberg Rd,2,t,770000.0,VB,Nelson,26-08-2017,5.3,3070.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,11364.0
23363,Ormond,9a Bewdley St,4,t,NaN,S,Jellis,26-08-2017,11.4,3204.0,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,3578.0
23384,Prahran,82 Murray St,2,h,1500000.0,VB,RT,26-08-2017,4.6,3181.0,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,7717.0
23397,Reservoir,5a Kyneton Av,3,u,635000.0,S,Barry,26-08-2017,12.0,3073.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,21650.0
23398,Reservoir,13 Lawley St,4,h,NaN,PI,Barry,26-08-2017,12.0,3073.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,21650.0
23409,Richmond,10/9 Westbank Tce,2,u,410000.0,PI,Jellis,26-08-2017,2.4,3121.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,14949.0
23412,Ringwood East,2/16 Bronhill Rd,4,t,850000.0,VB,McGrath,26-08-2017,21.3,3135.0,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Metropolitan,4407.0
23418,Rowville,8 Lakeside Bvd,3,h,905000.0,S,Biggin,26-08-2017,23.5,3178.0,NaN,NaN,NaN,NaN,NaN,NaN,South-Eastern Metropolitan,11667.0
23424,Sandringham,4 Gipsy Wy,2,t,NaN,SP,Buxton,26-08-2017,15.2,3191.0,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,4497.0
23437,South Morang,2/5 Briar Ct,2,u,310000.0,S,HAR,26-08-2017,20.5,3752.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,7969.0
23442,South Morang,18 Warbler Wk,3,h,691000.0,S,Millership,26-08-2017,20.5,3752.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,7969.0
23446,South Yarra,20/22 Mona Pl,2,u,500000.0,VB,Greg,26-08-2017,2.7,3141.0,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,14887.0
23449,St Albans,1/52 Conrad St,2,t,457500.0,S,Barry,26-08-2017,14.0,3021.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,14042.0
23453,St Albans,39b Power St,2,u,515000.0,PI,Brad,26-08-2017,14.0,3021.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,14042.0
23472,Sunshine West,65 Europa Bnd,1,h,460000.0,S,S&L,26-08-2017,10.5,3020.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,6763.0
23495,Templestowe Lower,1/207 Manningham Rd,2,u,550000.0,PI,Barry,26-08-2017,12.4,3107.0,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Metropolitan,5420.0
23499,Thornbury,1/128 Dundas St,2,t,770000.0,PI,McGrath,26-08-2017,7.0,3071.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,8870.0
23502,Thornbury,111 Pender St,2,t,858000.0,S,Jellis,26-08-2017,7.0,3071.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,8870.0
23508,Toorak,21/1059 Malvern Rd,2,u,720000.0,VB,Beller,26-08-2017,4.1,3142.0,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,7217.0
23531,Werribee,91 Latham St,4,h,540000.0,PI,Triwest,26-08-2017,14.7,3030.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,16166.0

In [39]:
#count the num of rows having > 5 missing values
#use len(df.index)
len(df[df.isnull().sum(axis=1)>5].index)

4278

In [40]:
#4278 rows having more than 5 the missing  values
# calculate percentage
100*(len(df[df.isnull().sum(axis=1)>5].index)/len(df.index))

18.16791948018856

In [41]:
# retaining the rows having <=5 NaNs
df=df[df.isnull().sum(axis=1)<=5]

# look at the summary again
round(100*(df.isnull().sum()/len(df.index)),2)

Suburb            0.00
Address           0.00
Rooms             0.00
Type              0.00
Price            21.71
Method            0.00
SellerG           0.00
Date              0.00
Distance          0.00
Postcode          0.00
Bedroom2          1.05
Bathroom          1.07
Car               1.81
Landsize          9.65
Lattitude         0.13
Longtitude        0.13
Regionname        0.00
Propertycount     0.00
dtype: float64

In [42]:
# removing NaN price in rows
df= df[~np.isnan(df['Price'])]

round(100*(df.isnull().sum()/len(df.index)),2)

Suburb           0.00
Address          0.00
Rooms            0.00
Type             0.00
Price            0.00
Method           0.00
SellerG          0.00
Date             0.00
Distance         0.00
Postcode         0.00
Bedroom2         1.05
Bathroom         1.07
Car              1.76
Landsize         9.83
Lattitude        0.15
Longtitude       0.15
Regionname       0.00
Propertycount    0.00
dtype: float64

In [43]:
len(df)

15086

In [44]:
df.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [45]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Propertycount
count,15086.000000,1.508600e+04,15086.000000,15086.000000,14927.000000,14925.000000,14820.000000,13603.000000,15064.000000,15064.000000,15086.000000
mean,2.932653,1.066695e+06,10.290753,3107.384330,2.913043,1.538492,1.615520,558.116371,-37.809849,144.996338,7491.225905
std,0.963214,6.389331e+05,6.070538,94.360707,0.964641,0.689311,0.955916,3987.326586,0.081152,0.106375,4395.533579
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.400000e+05,6.100000,3046.000000,2.000000,1.000000,1.000000,176.500000,-37.858100,144.931193,4380.000000
50%,3.000000,9.000000e+05,9.300000,3087.000000,3.000000,1.000000,2.000000,440.000000,-37.803625,145.000920,6567.000000
75%,3.000000,1.320000e+06,13.100000,3149.750000,3.000000,2.000000,2.000000,651.000000,-37.756270,145.060000,10331.000000
max,12.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,-37.408530,145.526350,21650.000000

In [46]:
df['Landsize'].describe()

count     13603.000000
mean        558.116371
std        3987.326586
min           0.000000
25%         176.500000
50%         440.000000
75%         651.000000
max      433014.000000
Name: Landsize, dtype: float64

Notice that minimum is 0, maximum is 433014, the mean is 558 and median is 440(50%). There is a significant variation in the 25th and 75th percentile as well(176 to 651).

Thus imputing with mean/ median seems quite biased. and so we should remove the NaNs

In [47]:
# removing NaNs in  Landsize:
df= df[~np.isnan(df['Landsize'])]

round(100*(df.isnull().sum()/len(df.index)),2)

Suburb           0.00
Address          0.00
Rooms            0.00
Type             0.00
Price            0.00
Method           0.00
SellerG          0.00
Date             0.00
Distance         0.00
Postcode         0.00
Bedroom2         0.00
Bathroom         0.01
Car              0.46
Landsize         0.00
Lattitude        0.16
Longtitude       0.16
Regionname       0.00
Propertycount    0.00
dtype: float64

In [48]:
len(df[~np.isnan(df['Landsize'])])

13603

In [49]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Regionname,Propertycount
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,2.0,1.0,1.0,202.0,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,2.0,1.0,0.0,156.0,-37.80790,144.99340,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,3.0,2.0,0.0,134.0,-37.80930,144.99440,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,04-03-2017,2.5,3067.0,3.0,2.0,1.0,94.0,-37.79690,144.99690,Northern Metropolitan,4019.0
6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,04-06-2016,2.5,3067.0,3.0,1.0,2.0,120.0,-37.80720,144.99410,Northern Metropolitan,4019.0
10,Abbotsford,129 Charles St,2,h,941000.0,S,Jellis,07-05-2016,2.5,3067.0,2.0,1.0,0.0,181.0,-37.80410,144.99530,Northern Metropolitan,4019.0
11,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,07-05-2016,2.5,3067.0,4.0,2.0,0.0,245.0,-37.80240,144.99930,Northern Metropolitan,4019.0
14,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,08-10-2016,2.5,3067.0,2.0,1.0,2.0,256.0,-37.80600,144.99540,Northern Metropolitan,4019.0
17,Abbotsford,6/241 Nicholson St,1,u,300000.0,S,Biggin,08-10-2016,2.5,3067.0,1.0,1.0,1.0,0.0,-37.80080,144.99730,Northern Metropolitan,4019.0
18,Abbotsford,10 Valiant St,2,h,1097000.0,S,Biggin,08-10-2016,2.5,3067.0,3.0,1.0,2.0,220.0,-37.80100,144.99890,Northern Metropolitan,4019.0
23,Abbotsford,411/8 Grosvenor St,2,u,700000.0,VB,Jellis,12-11-2016,2.5,3067.0,2.0,2.0,1.0,0.0,-37.81100,145.00670,Northern Metropolitan,4019.0
24,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12-11-2016,2.5,3067.0,3.0,2.0,2.0,214.0,-37.80850,144.99640,Northern Metropolitan,4019.0
25,Abbotsford,123/56 Nicholson St,2,u,750000.0,S,Biggin,12-11-2016,2.5,3067.0,2.0,2.0,1.0,0.0,-37.80780,144.99650,Northern Metropolitan,4019.0
28,Abbotsford,45 William St,2,h,1172500.0,S,Biggin,13-08-2016,2.5,3067.0,2.0,1.0,1.0,195.0,-37.80840,144.99730,Northern Metropolitan,4019.0
29,Abbotsford,7/20 Abbotsford St,1,u,441000.0,SP,Greg,14-05-2016,2.5,3067.0,1.0,1.0,1.0,0.0,-37.80160,144.99880,Northern Metropolitan,4019.0
30,Abbotsford,16 William St,2,h,1310000.0,S,Jellis,15-10-2016,2.5,3067.0,2.0,1.0,2.0,238.0,-37.80900,144.99760,Northern Metropolitan,4019.0
32,Abbotsford,42 Henry St,3,h,1200000.0,S,Jellis,16-07-2016,2.5,3067.0,3.0,2.0,1.0,113.0,-37.80560,144.99300,Northern Metropolitan,4019.0
35,Abbotsford,78 Yarra St,3,h,1176500.0,S,LITTLE,16-07-2016,2.5,3067.0,2.0,1.0,1.0,138.0,-37.80210,144.99650,Northern Metropolitan,4019.0
36,Abbotsford,196 Nicholson St,3,h,955000.0,S,Collins,17-09-2016,2.5,3067.0,3.0,1.0,0.0,183.0,-37.80220,144.99750,Northern Metropolitan,4019.0
37,Abbotsford,42 Valiant St,2,h,890000.0,S,Biggin,17-09-2016,2.5,3067.0,2.0,1.0,1.0,150.0,-37.80110,145.00040,Northern Metropolitan,4019.0
38,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18-03-2017,2.5,3067.0,4.0,2.0,2.0,780.0,-37.80730,144.99520,Northern Metropolitan,4019.0
40,Abbotsford,13/11 Nicholson St,3,t,900000.0,S,Beller,18-03-2017,2.5,3067.0,3.0,2.0,2.0,0.0,-37.80930,144.99590,Northern Metropolitan,4019.0
41,Abbotsford,138/56 Nicholson St,3,u,1090000.0,S,Jellis,18-03-2017,2.5,3067.0,3.0,2.0,2.0,4290.0,-37.80780,144.99650,Northern Metropolitan,4019.0
42,Abbotsford,6/219 Nicholson St,2,u,500000.0,S,Collins,18-06-2016,2.5,3067.0,2.0,1.0,1.0,0.0,-37.80150,144.99720,Northern Metropolitan,4019.0
43,Abbotsford,52a William St,2,h,1100000.0,PI,Biggin,18-06-2016,2.5,3067.0,2.0,2.0,1.0,124.0,-37.80790,144.99770,Northern Metropolitan,4019.0
44,Abbotsford,49 Park St,2,h,1315000.0,S,Marshall,19-11-2016,2.5,3067.0,2.0,1.0,0.0,147.0,-37.80800,144.99400,Northern Metropolitan,4019.0
48,Abbotsford,5/20 Abbotsford St,1,u,426000.0,SP,Greg,22-08-2016,2.5,3067.0,1.0,1.0,1.0,0.0,-37.80160,144.99880,Northern Metropolitan,4019.0
49,Abbotsford,48 Abbotsford St,3,h,1447500.0,PI,Nelson,22-08-2016,2.5,3067.0,3.0,3.0,1.0,166.0,-37.80170,145.00010,Northern Metropolitan,4019.0
50,Abbotsford,116/56 Nicholson St,1,u,457000.0,S,Jellis,22-08-2016,2.5,3067.0,1.0,1.0,1.0,0.0,-37.80780,144.99650,Northern Metropolitan,4019.0
51,Abbotsford,159 Park St,2,h,1135000.0,S,Nelson,22-08-2016,2.5,3067.0,2.0,2.0,2.0,98.0,-37.80050,144.99520,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23471,Sunshine North,5 Berkshire Rd,3,h,595000.0,SP,Barry,26-08-2017,10.5,3020.0,3.0,1.0,NaN,589.0,-37.76599,144.84445,Western Metropolitan,4217.0
23473,Sunshine West,24 Hilma St,4,h,682000.0,S,Barry,26-08-2017,10.5,3020.0,4.0,1.0,2.0,534.0,-37.79161,144.80461,Western Metropolitan,6763.0
23474,Sunshine West,16 Mudford St,3,h,640000.0,S,Bells,26-08-2017,10.5,3020.0,3.0,1.0,1.0,616.0,-37.79798,144.81529,Western Metropolitan,6763.0
23475,Surrey Hills,20 Albert Cr,4,h,2720000.0,S,Kay,26-08-2017,10.2,3127.0,4.0,3.0,2.0,1005.0,-37.82421,145.10352,Southern Metropolitan,5457.0
23476,Surrey Hills,46 Durham Rd,3,h,1715000.0,S,Noel,26-08-2017,10.2,3127.0,3.0,1.0,2.0,438.0,-37.83015,145.09035,Southern Metropolitan,5457.0
23479,Surrey Hills,3 Oak St,4,h,3100000.0,VB,Marshall,26-08-2017,10.2,3127.0,4.0,2.0,3.0,832.0,-37.83564,145.10919,Southern Metropolitan,5457.0
23482,Tarneit,27 McMahon Cr,3,h,350000.0,VB,S&L,26-08-2017,18.4,3029.0,3.0,1.0,1.0,466.0,-37.86744,144.65609,Western Metropolitan,10160.0
23488,Templestowe,10 Hathaway Cl,4,h,1753000.0,S,Barry,26-08-2017,15.5,3106.0,4.0,2.0,2.0,689.0,-37.76673,145.16555,Eastern Metropolitan,6202.0
23490,Templestowe Lower,20 Airds Rd,4,h,1745000.0,S,RT,26-08-2017,12.4,3107.0,4.0,2.0,2.0,741.0,-37.75843,145.10888,Eastern Metropolitan,5420.0
23491,Templestowe Lower,16 Benambra Dr,3,h,1190000.0,S,hockingstuart,26-08-2017,12.4,3107.0,3.0,1.0,1.0,723.0,-37.76684,145.11309,Eastern Metropolitan,5420.0
23492,Templestowe Lower,50 Caroline Dr,5,h,1400000.0,S,Barry,26-08-2017,12.4,3107.0,5.0,3.0,2.0,717.0,-37.76630,145.11320,Eastern Metropolitan,5420.0
23493,Templestowe Lower,7 Dove Ct,4,h,1288000.0,S,Barry,26-08-2017,12.4,3107.0,4.0,2.0,2.0,948.0,-37.76078,145.10696,Eastern Metropolitan,5420.0
23497,Thornbury,7 Ballantyne St,3,h,1450000.0,S,Woodards,26-08-2017,7.0,3071.0,3.0,1.0,1.0,312.0,-37.75870,144.99966,Northern Metropolitan,8870.0
23501,Thornbury,201 Gooch St,3,h,1271000.0,S,Nelson,26-08-2017,7.0,3071.0,3.0,1.0,2.0,470.0,-37.75937,145.01534,Northern Metropolitan,8870.0
23512,Tullamarine,7 Londrew Ct,3,h,540000.0,S,Barry,26-08-2017,12.9,3043.0,3.0,1.0,1.0,607.0,-37.69423,144.88002,Western Metropolitan,3296.0
23514,Vermont,73 Nurlendi Rd,4,h,1263500.0,S,Barry,26-08-2017,17.2,3133.0,4.0,2.0,2.0,791.0,-37.84467,145.19276,Eastern Metropolitan,4181.0
23518,Vermont South,9 Winswood Cl,4,h,1250000.0,PI,Philip,26-08-2017,17.2,3133.0,4.0,2.0,2.0,986.0,-37.84679,145.20051,Eastern Metropolitan,4280.0
23519,Viewbank,149 Graham Rd,5,h,1316000.0,SP,Nelson,26-08-2017,8.9,3084.0,5.0,3.0,3.0,696.0,-37.73501,145.08341,Eastern Metropolitan,2698.0
23521,Wantirna,16 chesterfield Ct,4,h,951000.0,S,Ray,26-08-2017,14.7,3152.0,4.0,2.0,2.0,704.0,-37.85639,145.23536,Eastern Metropolitan,5424.0
23523,Wantirna South,12 Armagh Cr,4,h,1323000.0,S,Barry,26-08-2017,14.7,3152.0,4.0,2.0,2.0,551.0,-37.87608,145.22390,Eastern Metropolitan,7082.0
23524,Wantirna South,34 Fewster Dr,3,h,970000.0,S,Barry,26-08-2017,14.7,3152.0,3.0,2.0,2.0,674.0,-37.88360,145.22805,Eastern Metropolitan,7082.0
23525,Wantirna South,15 Mara Cl,4,h,1330000.0,S,Barry,26-08-2017,14.7,3152.0,4.0,2.0,2.0,717.0,-37.86887,145.22116,Eastern Metropolitan,7082.0
23527,Watsonia,76 Kenmare St,2,h,650000.0,PI,Morrison,26-08-2017,14.5,3087.0,2.0,1.0,1.0,210.0,-37.70657,145.07878,Northern Metropolitan,2329.0
23532,Werribee,5 Nuragi Ct,4,h,635000.0,S,hockingstuart,26-08-2017,14.7,3030.0,4.0,2.0,1.0,662.0,-37.89327,144.64789,Western Metropolitan,16166.0
23535,Westmeadows,9 Black St,3,h,582000.0,S,Red,26-08-2017,16.5,3049.0,3.0,2.0,2.0,256.0,-37.67917,144.89390,Northern Metropolitan,2474.0
23537,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26-08-2017,16.7,3150.0,4.0,2.0,2.0,652.0,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
23538,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26-08-2017,6.8,3016.0,3.0,2.0,2.0,333.0,-37.85927,144.87904,Western Metropolitan,6380.0
23539,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26-08-2017,6.8,3016.0,3.0,2.0,4.0,436.0,-37.85274,144.88738,Western Metropolitan,6380.0
23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26-08-2017,6.8,3016.0,4.0,1.0,5.0,866.0,-37.85908,144.89299,Western Metropolitan,6380.0
23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,4.0,1.0,1.0,362.0,-37.81188,144.88449,Western Metropolitan,6543.0

In [52]:
df['Lattitude'].describe()

count    13581.000000
mean       -37.809204
std          0.079257
min        -38.182550
25%        -37.856820
50%        -37.802360
75%        -37.756400
max        -37.408530
Name: Lattitude, dtype: float64

In [54]:
df['Lattitude'].fillna(df['Lattitude'].mean(),inplace=True)

In [55]:
df['Lattitude'].mean()

-37.80920350636921

In [56]:
df.dtypes

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [58]:
df['Longtitude'].describe()

count    13581.000000
mean       144.995221
std          0.103913
min        144.431810
25%        144.929600
50%        145.000100
75%        145.058320
max        145.526350
Name: Longtitude, dtype: float64

In [59]:
df['Longtitude'].fillna(df['Longtitude'].mean(),inplace=True)

In [60]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Regionname,Propertycount
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,2.0,1.0,1.0,202.0,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,2.0,1.0,0.0,156.0,-37.80790,144.99340,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,3.0,2.0,0.0,134.0,-37.80930,144.99440,Northern Metropolitan,4019.0
5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,04-03-2017,2.5,3067.0,3.0,2.0,1.0,94.0,-37.79690,144.99690,Northern Metropolitan,4019.0
6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,04-06-2016,2.5,3067.0,3.0,1.0,2.0,120.0,-37.80720,144.99410,Northern Metropolitan,4019.0
10,Abbotsford,129 Charles St,2,h,941000.0,S,Jellis,07-05-2016,2.5,3067.0,2.0,1.0,0.0,181.0,-37.80410,144.99530,Northern Metropolitan,4019.0
11,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,07-05-2016,2.5,3067.0,4.0,2.0,0.0,245.0,-37.80240,144.99930,Northern Metropolitan,4019.0
14,Abbotsford,98 Charles St,2,h,1636000.0,S,Nelson,08-10-2016,2.5,3067.0,2.0,1.0,2.0,256.0,-37.80600,144.99540,Northern Metropolitan,4019.0
17,Abbotsford,6/241 Nicholson St,1,u,300000.0,S,Biggin,08-10-2016,2.5,3067.0,1.0,1.0,1.0,0.0,-37.80080,144.99730,Northern Metropolitan,4019.0
18,Abbotsford,10 Valiant St,2,h,1097000.0,S,Biggin,08-10-2016,2.5,3067.0,3.0,1.0,2.0,220.0,-37.80100,144.99890,Northern Metropolitan,4019.0
23,Abbotsford,411/8 Grosvenor St,2,u,700000.0,VB,Jellis,12-11-2016,2.5,3067.0,2.0,2.0,1.0,0.0,-37.81100,145.00670,Northern Metropolitan,4019.0
24,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12-11-2016,2.5,3067.0,3.0,2.0,2.0,214.0,-37.80850,144.99640,Northern Metropolitan,4019.0
25,Abbotsford,123/56 Nicholson St,2,u,750000.0,S,Biggin,12-11-2016,2.5,3067.0,2.0,2.0,1.0,0.0,-37.80780,144.99650,Northern Metropolitan,4019.0
28,Abbotsford,45 William St,2,h,1172500.0,S,Biggin,13-08-2016,2.5,3067.0,2.0,1.0,1.0,195.0,-37.80840,144.99730,Northern Metropolitan,4019.0
29,Abbotsford,7/20 Abbotsford St,1,u,441000.0,SP,Greg,14-05-2016,2.5,3067.0,1.0,1.0,1.0,0.0,-37.80160,144.99880,Northern Metropolitan,4019.0
30,Abbotsford,16 William St,2,h,1310000.0,S,Jellis,15-10-2016,2.5,3067.0,2.0,1.0,2.0,238.0,-37.80900,144.99760,Northern Metropolitan,4019.0
32,Abbotsford,42 Henry St,3,h,1200000.0,S,Jellis,16-07-2016,2.5,3067.0,3.0,2.0,1.0,113.0,-37.80560,144.99300,Northern Metropolitan,4019.0
35,Abbotsford,78 Yarra St,3,h,1176500.0,S,LITTLE,16-07-2016,2.5,3067.0,2.0,1.0,1.0,138.0,-37.80210,144.99650,Northern Metropolitan,4019.0
36,Abbotsford,196 Nicholson St,3,h,955000.0,S,Collins,17-09-2016,2.5,3067.0,3.0,1.0,0.0,183.0,-37.80220,144.99750,Northern Metropolitan,4019.0
37,Abbotsford,42 Valiant St,2,h,890000.0,S,Biggin,17-09-2016,2.5,3067.0,2.0,1.0,1.0,150.0,-37.80110,145.00040,Northern Metropolitan,4019.0
38,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18-03-2017,2.5,3067.0,4.0,2.0,2.0,780.0,-37.80730,144.99520,Northern Metropolitan,4019.0
40,Abbotsford,13/11 Nicholson St,3,t,900000.0,S,Beller,18-03-2017,2.5,3067.0,3.0,2.0,2.0,0.0,-37.80930,144.99590,Northern Metropolitan,4019.0
41,Abbotsford,138/56 Nicholson St,3,u,1090000.0,S,Jellis,18-03-2017,2.5,3067.0,3.0,2.0,2.0,4290.0,-37.80780,144.99650,Northern Metropolitan,4019.0
42,Abbotsford,6/219 Nicholson St,2,u,500000.0,S,Collins,18-06-2016,2.5,3067.0,2.0,1.0,1.0,0.0,-37.80150,144.99720,Northern Metropolitan,4019.0
43,Abbotsford,52a William St,2,h,1100000.0,PI,Biggin,18-06-2016,2.5,3067.0,2.0,2.0,1.0,124.0,-37.80790,144.99770,Northern Metropolitan,4019.0
44,Abbotsford,49 Park St,2,h,1315000.0,S,Marshall,19-11-2016,2.5,3067.0,2.0,1.0,0.0,147.0,-37.80800,144.99400,Northern Metropolitan,4019.0
48,Abbotsford,5/20 Abbotsford St,1,u,426000.0,SP,Greg,22-08-2016,2.5,3067.0,1.0,1.0,1.0,0.0,-37.80160,144.99880,Northern Metropolitan,4019.0
49,Abbotsford,48 Abbotsford St,3,h,1447500.0,PI,Nelson,22-08-2016,2.5,3067.0,3.0,3.0,1.0,166.0,-37.80170,145.00010,Northern Metropolitan,4019.0
50,Abbotsford,116/56 Nicholson St,1,u,457000.0,S,Jellis,22-08-2016,2.5,3067.0,1.0,1.0,1.0,0.0,-37.80780,144.99650,Northern Metropolitan,4019.0
51,Abbotsford,159 Park St,2,h,1135000.0,S,Nelson,22-08-2016,2.5,3067.0,2.0,2.0,2.0,98.0,-37.80050,144.99520,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23471,Sunshine North,5 Berkshire Rd,3,h,595000.0,SP,Barry,26-08-2017,10.5,3020.0,3.0,1.0,NaN,589.0,-37.76599,144.84445,Western Metropolitan,4217.0
23473,Sunshine West,24 Hilma St,4,h,682000.0,S,Barry,26-08-2017,10.5,3020.0,4.0,1.0,2.0,534.0,-37.79161,144.80461,Western Metropolitan,6763.0
23474,Sunshine West,16 Mudford St,3,h,640000.0,S,Bells,26-08-2017,10.5,3020.0,3.0,1.0,1.0,616.0,-37.79798,144.81529,Western Metropolitan,6763.0
23475,Surrey Hills,20 Albert Cr,4,h,2720000.0,S,Kay,26-08-2017,10.2,3127.0,4.0,3.0,2.0,1005.0,-37.82421,145.10352,Southern Metropolitan,5457.0
23476,Surrey Hills,46 Durham Rd,3,h,1715000.0,S,Noel,26-08-2017,10.2,3127.0,3.0,1.0,2.0,438.0,-37.83015,145.09035,Southern Metropolitan,5457.0
23479,Surrey Hills,3 Oak St,4,h,3100000.0,VB,Marshall,26-08-2017,10.2,3127.0,4.0,2.0,3.0,832.0,-37.83564,145.10919,Southern Metropolitan,5457.0
23482,Tarneit,27 McMahon Cr,3,h,350000.0,VB,S&L,26-08-2017,18.4,3029.0,3.0,1.0,1.0,466.0,-37.86744,144.65609,Western Metropolitan,10160.0
23488,Templestowe,10 Hathaway Cl,4,h,1753000.0,S,Barry,26-08-2017,15.5,3106.0,4.0,2.0,2.0,689.0,-37.76673,145.16555,Eastern Metropolitan,6202.0
23490,Templestowe Lower,20 Airds Rd,4,h,1745000.0,S,RT,26-08-2017,12.4,3107.0,4.0,2.0,2.0,741.0,-37.75843,145.10888,Eastern Metropolitan,5420.0
23491,Templestowe Lower,16 Benambra Dr,3,h,1190000.0,S,hockingstuart,26-08-2017,12.4,3107.0,3.0,1.0,1.0,723.0,-37.76684,145.11309,Eastern Metropolitan,5420.0
23492,Templestowe Lower,50 Caroline Dr,5,h,1400000.0,S,Barry,26-08-2017,12.4,3107.0,5.0,3.0,2.0,717.0,-37.76630,145.11320,Eastern Metropolitan,5420.0
23493,Templestowe Lower,7 Dove Ct,4,h,1288000.0,S,Barry,26-08-2017,12.4,3107.0,4.0,2.0,2.0,948.0,-37.76078,145.10696,Eastern Metropolitan,5420.0
23497,Thornbury,7 Ballantyne St,3,h,1450000.0,S,Woodards,26-08-2017,7.0,3071.0,3.0,1.0,1.0,312.0,-37.75870,144.99966,Northern Metropolitan,8870.0
23501,Thornbury,201 Gooch St,3,h,1271000.0,S,Nelson,26-08-2017,7.0,3071.0,3.0,1.0,2.0,470.0,-37.75937,145.01534,Northern Metropolitan,8870.0
23512,Tullamarine,7 Londrew Ct,3,h,540000.0,S,Barry,26-08-2017,12.9,3043.0,3.0,1.0,1.0,607.0,-37.69423,144.88002,Western Metropolitan,3296.0
23514,Vermont,73 Nurlendi Rd,4,h,1263500.0,S,Barry,26-08-2017,17.2,3133.0,4.0,2.0,2.0,791.0,-37.84467,145.19276,Eastern Metropolitan,4181.0
23518,Vermont South,9 Winswood Cl,4,h,1250000.0,PI,Philip,26-08-2017,17.2,3133.0,4.0,2.0,2.0,986.0,-37.84679,145.20051,Eastern Metropolitan,4280.0
23519,Viewbank,149 Graham Rd,5,h,1316000.0,SP,Nelson,26-08-2017,8.9,3084.0,5.0,3.0,3.0,696.0,-37.73501,145.08341,Eastern Metropolitan,2698.0
23521,Wantirna,16 chesterfield Ct,4,h,951000.0,S,Ray,26-08-2017,14.7,3152.0,4.0,2.0,2.0,704.0,-37.85639,145.23536,Eastern Metropolitan,5424.0
23523,Wantirna South,12 Armagh Cr,4,h,1323000.0,S,Barry,26-08-2017,14.7,3152.0,4.0,2.0,2.0,551.0,-37.87608,145.22390,Eastern Metropolitan,7082.0
23524,Wantirna South,34 Fewster Dr,3,h,970000.0,S,Barry,26-08-2017,14.7,3152.0,3.0,2.0,2.0,674.0,-37.88360,145.22805,Eastern Metropolitan,7082.0
23525,Wantirna South,15 Mara Cl,4,h,1330000.0,S,Barry,26-08-2017,14.7,3152.0,4.0,2.0,2.0,717.0,-37.86887,145.22116,Eastern Metropolitan,7082.0
23527,Watsonia,76 Kenmare St,2,h,650000.0,PI,Morrison,26-08-2017,14.5,3087.0,2.0,1.0,1.0,210.0,-37.70657,145.07878,Northern Metropolitan,2329.0
23532,Werribee,5 Nuragi Ct,4,h,635000.0,S,hockingstuart,26-08-2017,14.7,3030.0,4.0,2.0,1.0,662.0,-37.89327,144.64789,Western Metropolitan,16166.0
23535,Westmeadows,9 Black St,3,h,582000.0,S,Red,26-08-2017,16.5,3049.0,3.0,2.0,2.0,256.0,-37.67917,144.89390,Northern Metropolitan,2474.0
23537,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26-08-2017,16.7,3150.0,4.0,2.0,2.0,652.0,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
23538,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26-08-2017,6.8,3016.0,3.0,2.0,2.0,333.0,-37.85927,144.87904,Western Metropolitan,6380.0
23539,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26-08-2017,6.8,3016.0,3.0,2.0,4.0,436.0,-37.85274,144.88738,Western Metropolitan,6380.0
23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26-08-2017,6.8,3016.0,4.0,1.0,5.0,866.0,-37.85908,144.89299,Western Metropolitan,6380.0
23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26-08-2017,6.3,3013.0,4.0,1.0,1.0,362.0,-37.81188,144.88449,Western Metropolitan,6543.0

In [71]:
df['Car'].describe()

count     13540.0
unique       11.0
top           2.0
freq       5606.0
Name: Car, dtype: float64

In [63]:
#converting to type 'Category'
df['Car']=df['Car'].astype('category')

In [66]:
df['Car'].head()

1    1.0
2    0.0
4    0.0
5    1.0
6    2.0
Name: Car, dtype: category
Categories (11, float64): [0.0, 1.0, 2.0, 3.0, ..., 7.0, 8.0, 9.0, 10.0]

In [67]:
df['Car'].unique()

[1.0, 0.0, 2.0, 6.0, 5.0, ..., 8.0, 7.0, 9.0, 10.0, NaN]
Length: 12
Categories (11, float64): [1.0, 0.0, 2.0, 6.0, ..., 8.0, 7.0, 9.0, 10.0]

In [69]:

df['Car'].nunique()

11

In [70]:
df['Car'].value_counts()

2.0     5606
1.0     5515
0.0     1026
3.0      748
4.0      507
5.0       63
6.0       54
8.0        9
7.0        8
10.0       3
9.0        1
Name: Car, dtype: int64

In [72]:
df['Car'].fillna(2.0,inplace=True)

In [73]:
df['Bathroom'].describe()

count    13602.000000
mean         1.534921
std          0.691834
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          8.000000
Name: Bathroom, dtype: float64

In [74]:
#converting to type 'Category'
df['Bathroom']=df['Bathroom'].astype('category')

In [75]:
df['Bathroom'].head()

1    1.0
2    1.0
4    2.0
5    2.0
6    1.0
Name: Bathroom, dtype: category
Categories (9, float64): [0.0, 1.0, 2.0, 3.0, ..., 5.0, 6.0, 7.0, 8.0]

In [76]:
df['Bathroom'].unique()

[1.0, 2.0, 3.0, 4.0, 0.0, 7.0, 5.0, 6.0, 8.0, NaN]
Categories (9, float64): [1.0, 2.0, 3.0, 4.0, ..., 7.0, 5.0, 6.0, 8.0]

In [77]:
df['Bathroom'].nunique()

9

In [79]:
df['Bathroom'].value_counts()

1.0    7517
2.0    4987
3.0     921
4.0     106
0.0      34
5.0      28
6.0       5
8.0       2
7.0       2
Name: Bathroom, dtype: int64

In [80]:
df['Bathroom'].fillna(1.0,inplace=True)