In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df= pd.read_csv('F://Final.csv')

In [3]:
df

,Audi,1968,Diesel,20.38,A3,3491000.0,5,Automatic,Unnamed: 8,35 TDI Premium Plus,Unnamed: 10
0,Audi,1968,Diesel,20.38,A3,3669000.0,5,Automatic,NaN,35 TDI Technology,NaN
1,Audi,1395,Petrol,19.2,A3,3310000.0,5,Automatic,NaN,35 TFSI Premium Plus,NaN
2,Audi,1395,Petrol,19.2,A3,3510000.0,5,Automatic,NaN,35 TFSI Technology,NaN
3,Audi,1968,Diesel,15.73,Q3,3653000.0,5,Manual,NaN,30 TDI Premium FWD,NaN
4,Audi,1968,Diesel,15.73,Q3,3968000.0,5,Automatic,NaN,35 TDI quattro Premium Plus,NaN
5,Audi,1395,Petrol,16.9,Q3,3473000.0,5,Automatic,NaN,30 TFSI Premium,NaN
6,Audi,1968,Diesel,16.9,Q3,4076000.0,5,Automatic,NaN,2.0 TDI Design Edition,NaN
7,Audi,1968,Diesel,18.25,A4,4337000.0,5,Automatic,NaN,35 TDI Premium Plus,NaN
8,Audi,1395,Petrol,17.84,A4,4147000.0,5,Automatic,NaN,30 TFSI Premium Plus,NaN
9,Audi,1395,Petrol,17.84,A4,4505000.0,5,Automatic,NaN,30 TFSI Technology Pack,NaN
10,Audi,1968,Diesel,16.55,A4,4694000.0,5,Automatic,NaN,35 TDI Technology Pack,NaN
11,Audi,1798,Petrol,16.6,A3 Cabriolet,4486219.0,4,Automatic,NaN,40 TFSI,NaN
12,Audi,1968,Diesel,16.9,Q5,5527000.0,5,Automatic,NaN,35 TDI Premium Plus,NaN
13,Audi,1968,Diesel,15.73,Q5,5979000.0,5,Automatic,NaN,35 TDI Technology,NaN
14,Audi,1984,Petrol,12.44,Q5,5527000.0,5,Automatic,NaN,45 TFSI Premium Plus,NaN
15,Audi,1984,Petrol,12.44,Q5,5979000.0,5,Automatic,NaN,45 TFSI Technology,NaN
16,Audi,1968,Diesel,19.2,A5,5540000.0,5,Automatic,NaN,Sportback,NaN
17,Audi,1968,Diesel,18.53,A6,5669000.0,5,Automatic,NaN,35 TDI Matrix,NaN
18,Audi,1798,Petrol,15.26,A6,5588000.0,5,Automatic,NaN,35 TFSI Matrix,NaN
19,Audi,1984,Petrol,14.33,TT,6543000.0,5,Automatic,NaN,45 TFSI,NaN
20,Audi,1968,Diesel,17.2,A5 Cabriolet,6924000.0,4,Automatic,NaN,2.0 TDI,NaN
21,Audi,3993,Petrol,9.4,A8L,14945000.0,7,Automatic,NaN,60 TFSI,NaN
22,Audi,2967,Diesel,16.77,A8L,11766000.0,7,Automatic,NaN,50 TDI,NaN
23,Audi,4134,Diesel,9.5,A8L,14334000.0,7,Automatic,NaN,60 TDI,NaN
24,Audi,6299,Petrol,15.7,A8L,20353000.0,7,Automatic,NaN,W12,NaN
25,Audi,2967,Diesel,16.77,A8L,12275000.0,7,Automatic,NaN,50 TDI Plus,NaN
26,Hyundai,814 cc,Petrol,21.1,Hyundai Eon,332900.0,5,Manual,NaN,NaN,D-Lite ...
27,Hyundai,814 cc,Petrol,21.1,Hyundai Eon,369698.0,5,Manual,NaN,NaN,D-Lite + ...
28,Hyundai,814 cc,Petrol,21.1,Hyundai Eon,383562.0,5,Manual,NaN,NaN,Era + ...
29,Hyundai,814 cc,Petrol,21.1,Hyundai Eon,414855.0,5,Manual,NaN,NaN,Magna + ...
...,...,...,...,...,...,...,...,...,...,...,...
470,Volkswagen,1498 cc,Petrol,20.6,Volkswagen Vento,1164000.0,5,Manual,NaN,NaN,1.5 TDI Highli...
471,Volkswagen,1498 cc,Petrol,21.5,Volkswagen Vento,1196000.0,5,Automatic,NaN,NaN,1.5 TDI Comfor...
472,Volkswagen,1498 cc,Petrol,21.5,Volkswagen Vento,1289000.0,5,Automatic,NaN,NaN,1.5 TDI Highli...
473,Volkswagen,1598 cc,Petrol,16.0,Volkswagen Vento,832500.0,5,Manual,NaN,NaN,1.6 MPI Trendl...
474,Volkswagen,1598 cc,Petrol,16.0,Volkswagen Vento,929900.0,5,Manual,NaN,NaN,1.6 MPI Comfor...
475,Volkswagen,1598 cc,Petrol,16.0,Volkswagen Vento,999900.0,5,Manual,NaN,NaN,1.6 MPI Highli...
476,Volkswagen,1197 cc,Diesel,18.1,Volkswagen Vento,1059000.0,5,Automatic,NaN,NaN,1.2 TSI Comfor...
477,Volkswagen,1197 cc,Diesel,18.1,Volkswagen Vento,1151000.0,5,Automatic,NaN,NaN,1.2 TSI Highli...
478,Volkswagen,1498 cc,Diesel,20.6,Volkswagen Vento,1267000.0,5,Manual,NaN,NaN,1.5L TDI Highl...
479,Volkswagen,1598 cc,Diesel,16.0,Volkswagen Vento,1127000.0,5,Manual,NaN,NaN,1.6L MPI Highl...
480,Volkswagen,1197 cc,Diesel,18.1,Volkswagen Vento,1254000.0,5,Automatic,NaN,NaN,1.2 TSI Highli...
481,Volkswagen,1498 cc,Diesel,20.6,Volkswagen Vento,1392000.0,5,Automatic,NaN,NaN,1.5L TDI Highl...
482,Volkswagen,1498 cc,Diesel,21.5,Volkswagen Vento,1289000.0,5,Automatic,NaN,NaN,Sports Edition...
483,Volkswagen,1197 cc,Diesel,18.1,Volkswagen Vento,999900.0,5,Manual,NaN,NaN,Sports Edition...
484,Volkswagen,1968 cc,Diesel,17.0,Volkswagen Tiguan,2749074.0,5,Automatic,NaN,NaN,Comfortline 2....
485,Volkswagen,1968 cc,Diesel,17.0,Volkswagen Tiguan,3087611.0,5,Automatic,NaN,NaN,Highline 2.0L ...
486,Volkswagen,1968 cc,Diesel,17.4,Volkswagen Passat,1901500.0,5,Automatic,NaN,NaN,2.0 TDI Comfor...
487,Volkswagen,1968 cc,Diesel,17.4,Volkswagen Passat,2999000.0,5,Automatic,NaN,NaN,2.0 TDI Highli...
488,Volkswagen,999 cc,Petrol,18.7,Volkswagen Polo,553500.0,5,Manual,NaN,NaN,Trendline 1L (...
489,Volkswagen,999 cc,Petrol,18.7,Volkswagen Polo,623000.0,5,Manual,NaN,NaN,Comfortline 1L...
490,Volkswagen,999 cc,Petrol,18.7,Volkswagen Polo,714500.0,5,Manual,NaN,NaN,Highline 1L (P...
491,Volkswagen,1498 cc,Petrol,20.1,Volkswagen Polo,704000.0,5,Manual,NaN,NaN,Trendline 1.5L...
492,Volkswagen,1498 cc,Petrol,20.1,Volkswagen Polo,867200.0,5,Manual,NaN,NaN,Highline1.5L (...
493,Volkswagen,1498 cc,Petrol,20.1,Volkswagen Polo,795500.0,5,Manual,NaN,NaN,Comfortline 1....
494,Volkswagen,999 cc,Diesel,18.7,Volkswagen Polo,730978.0,5,Manual,NaN,NaN,Allstar 1L (P)...
495,Volkswagen,1498 cc,Diesel,20.1,Volkswagen Polo,885012.0,5,Manual,NaN,NaN,Allstar 1.5L (...
496,Volkswagen,999 cc,Diesel,18.7,Volkswagen Polo,737000.0,5,Manual,NaN,NaN,Highline Plus ...
497,Volkswagen,1498 cc,Diesel,20.1,Volkswagen Polo,890200.0,5,Manual,NaN,NaN,Highline Plus ...
498,Volkswagen,999 cc,Diesel,18.7,Volkswagen Polo,714500.0,5,Manual,NaN,NaN,Sports Edition...
499,Volkswagen,1498 cc,Diesel,20.1,Volkswagen Polo,867200.0,5,Manual,NaN,NaN,Sports Edition...

In [4]:
df=df.drop('Unnamed: 8',axis=1)
df.head(3)

,Audi,1968,Diesel,20.38,A3,3491000.0,5,Automatic,35 TDI Premium Plus,Unnamed: 10
0,Audi,1968,Diesel,20.38,A3,3669000.0,5,Automatic,35 TDI Technology,NaN
1,Audi,1395,Petrol,19.2,A3,3310000.0,5,Automatic,35 TFSI Premium Plus,NaN
2,Audi,1395,Petrol,19.2,A3,3510000.0,5,Automatic,35 TFSI Technology,NaN

In [5]:
df.keys()

Index(['Audi', '1968', 'Diesel', '20.38', 'A3', '3491000.0', '5', 'Automatic',
       '35 TDI Premium Plus', 'Unnamed: 10'],
      dtype='object')

In [6]:
df.columns=['Brand','CC','EngineType','Mileage','Model','Price','SeatCapacity','Transmission','Variant1','Variant2']

In [7]:
df.head(3)

,Brand,CC,EngineType,Mileage,Model,Price,SeatCapacity,Transmission,Variant1,Variant2
0,Audi,1968,Diesel,20.38,A3,3669000.0,5,Automatic,35 TDI Technology,NaN
1,Audi,1395,Petrol,19.2,A3,3310000.0,5,Automatic,35 TFSI Premium Plus,NaN
2,Audi,1395,Petrol,19.2,A3,3510000.0,5,Automatic,35 TFSI Technology,NaN

In [8]:
df.isnull().sum()

Brand             0
CC                0
EngineType        0
Mileage           0
Model             0
Price             0
SeatCapacity      0
Transmission      0
Variant1        198
Variant2        302
dtype: int64

In [9]:
round(100*(df.isnull().sum()/len(df.index)),2)

Brand            0.0
CC               0.0
EngineType       0.0
Mileage          0.0
Model            0.0
Price            0.0
SeatCapacity     0.0
Transmission     0.0
Variant1        39.6
Variant2        60.4
dtype: float64

In [10]:
#removing cc in CC columns:
cc=[]
for i in df['CC']:
    i=str(i).replace('cc','')
    cc.append(i)

In [11]:
df['CC']=cc

In [12]:
df

,Brand,CC,EngineType,Mileage,Model,Price,SeatCapacity,Transmission,Variant1,Variant2
0,Audi,1968,Diesel,20.38,A3,3669000.0,5,Automatic,35 TDI Technology,NaN
1,Audi,1395,Petrol,19.2,A3,3310000.0,5,Automatic,35 TFSI Premium Plus,NaN
2,Audi,1395,Petrol,19.2,A3,3510000.0,5,Automatic,35 TFSI Technology,NaN
3,Audi,1968,Diesel,15.73,Q3,3653000.0,5,Manual,30 TDI Premium FWD,NaN
4,Audi,1968,Diesel,15.73,Q3,3968000.0,5,Automatic,35 TDI quattro Premium Plus,NaN
5,Audi,1395,Petrol,16.9,Q3,3473000.0,5,Automatic,30 TFSI Premium,NaN
6,Audi,1968,Diesel,16.9,Q3,4076000.0,5,Automatic,2.0 TDI Design Edition,NaN
7,Audi,1968,Diesel,18.25,A4,4337000.0,5,Automatic,35 TDI Premium Plus,NaN
8,Audi,1395,Petrol,17.84,A4,4147000.0,5,Automatic,30 TFSI Premium Plus,NaN
9,Audi,1395,Petrol,17.84,A4,4505000.0,5,Automatic,30 TFSI Technology Pack,NaN
10,Audi,1968,Diesel,16.55,A4,4694000.0,5,Automatic,35 TDI Technology Pack,NaN
11,Audi,1798,Petrol,16.6,A3 Cabriolet,4486219.0,4,Automatic,40 TFSI,NaN
12,Audi,1968,Diesel,16.9,Q5,5527000.0,5,Automatic,35 TDI Premium Plus,NaN
13,Audi,1968,Diesel,15.73,Q5,5979000.0,5,Automatic,35 TDI Technology,NaN
14,Audi,1984,Petrol,12.44,Q5,5527000.0,5,Automatic,45 TFSI Premium Plus,NaN
15,Audi,1984,Petrol,12.44,Q5,5979000.0,5,Automatic,45 TFSI Technology,NaN
16,Audi,1968,Diesel,19.2,A5,5540000.0,5,Automatic,Sportback,NaN
17,Audi,1968,Diesel,18.53,A6,5669000.0,5,Automatic,35 TDI Matrix,NaN
18,Audi,1798,Petrol,15.26,A6,5588000.0,5,Automatic,35 TFSI Matrix,NaN
19,Audi,1984,Petrol,14.33,TT,6543000.0,5,Automatic,45 TFSI,NaN
20,Audi,1968,Diesel,17.2,A5 Cabriolet,6924000.0,4,Automatic,2.0 TDI,NaN
21,Audi,3993,Petrol,9.4,A8L,14945000.0,7,Automatic,60 TFSI,NaN
22,Audi,2967,Diesel,16.77,A8L,11766000.0,7,Automatic,50 TDI,NaN
23,Audi,4134,Diesel,9.5,A8L,14334000.0,7,Automatic,60 TDI,NaN
24,Audi,6299,Petrol,15.7,A8L,20353000.0,7,Automatic,W12,NaN
25,Audi,2967,Diesel,16.77,A8L,12275000.0,7,Automatic,50 TDI Plus,NaN
26,Hyundai,814,Petrol,21.1,Hyundai Eon,332900.0,5,Manual,NaN,D-Lite ...
27,Hyundai,814,Petrol,21.1,Hyundai Eon,369698.0,5,Manual,NaN,D-Lite + ...
28,Hyundai,814,Petrol,21.1,Hyundai Eon,383562.0,5,Manual,NaN,Era + ...
29,Hyundai,814,Petrol,21.1,Hyundai Eon,414855.0,5,Manual,NaN,Magna + ...
...,...,...,...,...,...,...,...,...,...,...
470,Volkswagen,1498,Petrol,20.6,Volkswagen Vento,1164000.0,5,Manual,NaN,1.5 TDI Highli...
471,Volkswagen,1498,Petrol,21.5,Volkswagen Vento,1196000.0,5,Automatic,NaN,1.5 TDI Comfor...
472,Volkswagen,1498,Petrol,21.5,Volkswagen Vento,1289000.0,5,Automatic,NaN,1.5 TDI Highli...
473,Volkswagen,1598,Petrol,16.0,Volkswagen Vento,832500.0,5,Manual,NaN,1.6 MPI Trendl...
474,Volkswagen,1598,Petrol,16.0,Volkswagen Vento,929900.0,5,Manual,NaN,1.6 MPI Comfor...
475,Volkswagen,1598,Petrol,16.0,Volkswagen Vento,999900.0,5,Manual,NaN,1.6 MPI Highli...
476,Volkswagen,1197,Diesel,18.1,Volkswagen Vento,1059000.0,5,Automatic,NaN,1.2 TSI Comfor...
477,Volkswagen,1197,Diesel,18.1,Volkswagen Vento,1151000.0,5,Automatic,NaN,1.2 TSI Highli...
478,Volkswagen,1498,Diesel,20.6,Volkswagen Vento,1267000.0,5,Manual,NaN,1.5L TDI Highl...
479,Volkswagen,1598,Diesel,16.0,Volkswagen Vento,1127000.0,5,Manual,NaN,1.6L MPI Highl...
480,Volkswagen,1197,Diesel,18.1,Volkswagen Vento,1254000.0,5,Automatic,NaN,1.2 TSI Highli...
481,Volkswagen,1498,Diesel,20.6,Volkswagen Vento,1392000.0,5,Automatic,NaN,1.5L TDI Highl...
482,Volkswagen,1498,Diesel,21.5,Volkswagen Vento,1289000.0,5,Automatic,NaN,Sports Edition...
483,Volkswagen,1197,Diesel,18.1,Volkswagen Vento,999900.0,5,Manual,NaN,Sports Edition...
484,Volkswagen,1968,Diesel,17.0,Volkswagen Tiguan,2749074.0,5,Automatic,NaN,Comfortline 2....
485,Volkswagen,1968,Diesel,17.0,Volkswagen Tiguan,3087611.0,5,Automatic,NaN,Highline 2.0L ...
486,Volkswagen,1968,Diesel,17.4,Volkswagen Passat,1901500.0,5,Automatic,NaN,2.0 TDI Comfor...
487,Volkswagen,1968,Diesel,17.4,Volkswagen Passat,2999000.0,5,Automatic,NaN,2.0 TDI Highli...
488,Volkswagen,999,Petrol,18.7,Volkswagen Polo,553500.0,5,Manual,NaN,Trendline 1L (...
489,Volkswagen,999,Petrol,18.7,Volkswagen Polo,623000.0,5,Manual,NaN,Comfortline 1L...
490,Volkswagen,999,Petrol,18.7,Volkswagen Polo,714500.0,5,Manual,NaN,Highline 1L (P...
491,Volkswagen,1498,Petrol,20.1,Volkswagen Polo,704000.0,5,Manual,NaN,Trendline 1.5L...
492,Volkswagen,1498,Petrol,20.1,Volkswagen Polo,867200.0,5,Manual,NaN,Highline1.5L (...
493,Volkswagen,1498,Petrol,20.1,Volkswagen Polo,795500.0,5,Manual,NaN,Comfortline 1....
494,Volkswagen,999,Diesel,18.7,Volkswagen Polo,730978.0,5,Manual,NaN,Allstar 1L (P)...
495,Volkswagen,1498,Diesel,20.1,Volkswagen Polo,885012.0,5,Manual,NaN,Allstar 1.5L (...
496,Volkswagen,999,Diesel,18.7,Volkswagen Polo,737000.0,5,Manual,NaN,Highline Plus ...
497,Volkswagen,1498,Diesel,20.1,Volkswagen Polo,890200.0,5,Manual,NaN,Highline Plus ...
498,Volkswagen,999,Diesel,18.7,Volkswagen Polo,714500.0,5,Manual,NaN,Sports Edition...
499,Volkswagen,1498,Diesel,20.1,Volkswagen Polo,867200.0,5,Manual,NaN,Sports Edition...

In [13]:
df.EngineType.value_counts()

Petrol     277
Diesel     191
 Petrol     11
CNG         10
 Diesel      9
Hybrid       2
Name: EngineType, dtype: int64

In [14]:
typ=[]
for i in df['EngineType']:
    i=str(i).replace(' ','')
    typ.append(i)

In [15]:
df['EngineType']=typ

In [16]:
df.EngineType.value_counts()

Petrol    288
Diesel    200
CNG        10
Hybrid      2
Name: EngineType, dtype: int64

In [20]:
at=[]
for i in df['Transmission']:
    i=str(i).replace(' ','')
    at.append(i)

df['Transmission']=at
df.Transmission.value_counts()

#or

#df['Transmission']=df['Transmission'].apply(lambda X: X.strip())

Manual       327
Automatic    173
Name: Transmission, dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
Brand           500 non-null object
CC              500 non-null int32
EngineType      500 non-null object
Mileage         500 non-null object
Model           500 non-null object
Price           500 non-null float64
SeatCapacity    500 non-null int64
Transmission    500 non-null object
Variant1        302 non-null object
Variant2        198 non-null object
dtypes: float64(1), int32(1), int64(1), object(7)
memory usage: 37.2+ KB

In [18]:
df['CC']=df.CC.astype(int)
df['Mileage']=df.Mileage.astype(float)
#df['Transmission']=df.Transmission.astype(int)

ValueError: could not convert string to float: 'Nissan Sunny'

In [23]:
# In mileaage 'Nissan Sunny' is coming to remove that we need type the following code:

df['Mileage']=pd.to_numeric(df['Mileage'],errors='coerce')

In [24]:
df['Mileage']=df.Mileage.astype(float)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
Brand           500 non-null object
CC              500 non-null int32
EngineType      500 non-null object
Mileage         499 non-null float64
Model           500 non-null object
Price           500 non-null float64
SeatCapacity    500 non-null int64
Transmission    500 non-null object
Variant1        302 non-null object
Variant2        198 non-null object
dtypes: float64(2), int32(1), int64(1), object(6)
memory usage: 37.2+ KB

In [26]:
x=df['Mileage'].mean()

19.672985971943937

In [27]:
df["Mileage"].fillna("19.67", inplace = True)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
Brand           500 non-null object
CC              500 non-null int32
EngineType      500 non-null object
Mileage         500 non-null object
Model           500 non-null object
Price           500 non-null float64
SeatCapacity    500 non-null int64
Transmission    500 non-null object
Variant1        302 non-null object
Variant2        198 non-null object
dtypes: float64(1), int32(1), int64(1), object(7)
memory usage: 37.2+ KB

In [32]:
df['Variant']=df['Variant1'].combine_first(df['Variant2'])
# we can also use combine_firts use fillna

,Variant1,Variant2,Variant
0,35 TDI Technology,NaN,35 TDI Technology
1,35 TFSI Premium Plus,NaN,35 TFSI Premium Plus
2,35 TFSI Technology,NaN,35 TFSI Technology
3,30 TDI Premium FWD,NaN,30 TDI Premium FWD
4,35 TDI quattro Premium Plus,NaN,35 TDI quattro Premium Plus
5,30 TFSI Premium,NaN,30 TFSI Premium
6,2.0 TDI Design Edition,NaN,2.0 TDI Design Edition
7,35 TDI Premium Plus,NaN,35 TDI Premium Plus
8,30 TFSI Premium Plus,NaN,30 TFSI Premium Plus
9,30 TFSI Technology Pack,NaN,30 TFSI Technology Pack
10,35 TDI Technology Pack,NaN,35 TDI Technology Pack
11,40 TFSI,NaN,40 TFSI
12,35 TDI Premium Plus,NaN,35 TDI Premium Plus
13,35 TDI Technology,NaN,35 TDI Technology
14,45 TFSI Premium Plus,NaN,45 TFSI Premium Plus
15,45 TFSI Technology,NaN,45 TFSI Technology
16,Sportback,NaN,Sportback
17,35 TDI Matrix,NaN,35 TDI Matrix
18,35 TFSI Matrix,NaN,35 TFSI Matrix
19,45 TFSI,NaN,45 TFSI
20,2.0 TDI,NaN,2.0 TDI
21,60 TFSI,NaN,60 TFSI
22,50 TDI,NaN,50 TDI
23,60 TDI,NaN,60 TDI
24,W12,NaN,W12
25,50 TDI Plus,NaN,50 TDI Plus
26,NaN,D-Lite ...,D-Lite ...
27,NaN,D-Lite + ...,D-Lite + ...
28,NaN,Era + ...,Era + ...
29,NaN,Magna + ...,Magna + ...
...,...,...,...
470,NaN,1.5 TDI Highli...,1.5 TDI Highli...
471,NaN,1.5 TDI Comfor...,1.5 TDI Comfor...
472,NaN,1.5 TDI Highli...,1.5 TDI Highli...
473,NaN,1.6 MPI Trendl...,1.6 MPI Trendl...
474,NaN,1.6 MPI Comfor...,1.6 MPI Comfor...
475,NaN,1.6 MPI Highli...,1.6 MPI Highli...
476,NaN,1.2 TSI Comfor...,1.2 TSI Comfor...
477,NaN,1.2 TSI Highli...,1.2 TSI Highli...
478,NaN,1.5L TDI Highl...,1.5L TDI Highl...
479,NaN,1.6L MPI Highl...,1.6L MPI Highl...
480,NaN,1.2 TSI Highli...,1.2 TSI Highli...
481,NaN,1.5L TDI Highl...,1.5L TDI Highl...
482,NaN,Sports Edition...,Sports Edition...
483,NaN,Sports Edition...,Sports Edition...
484,NaN,Comfortline 2....,Comfortline 2....
485,NaN,Highline 2.0L ...,Highline 2.0L ...
486,NaN,2.0 TDI Comfor...,2.0 TDI Comfor...
487,NaN,2.0 TDI Highli...,2.0 TDI Highli...
488,NaN,Trendline 1L (...,Trendline 1L (...
489,NaN,Comfortline 1L...,Comfortline 1L...
490,NaN,Highline 1L (P...,Highline 1L (P...
491,NaN,Trendline 1.5L...,Trendline 1.5L...
492,NaN,Highline1.5L (...,Highline1.5L (...
493,NaN,Comfortline 1....,Comfortline 1....
494,NaN,Allstar 1L (P)...,Allstar 1L (P)...
495,NaN,Allstar 1.5L (...,Allstar 1.5L (...
496,NaN,Highline Plus ...,Highline Plus ...
497,NaN,Highline Plus ...,Highline Plus ...
498,NaN,Sports Edition...,Sports Edition...
499,NaN,Sports Edition...,Sports Edition...

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
Brand           500 non-null object
CC              500 non-null int32
EngineType      500 non-null object
Mileage         500 non-null object
Model           500 non-null object
Price           500 non-null float64
SeatCapacity    500 non-null int64
Transmission    500 non-null object
Variant1        302 non-null object
Variant2        198 non-null object
Variant         500 non-null object
dtypes: float64(1), int32(1), int64(1), object(8)
memory usage: 41.1+ KB

In [36]:
df=df.drop('Variant1',axis=1)
df=df.drop('Variant2',axis=1)

In [37]:
df.head()

,Brand,CC,EngineType,Mileage,Model,Price,SeatCapacity,Transmission,Variant
0,Audi,1968,Diesel,20.38,A3,3669000.0,5,Automatic,35 TDI Technology
1,Audi,1395,Petrol,19.2,A3,3310000.0,5,Automatic,35 TFSI Premium Plus
2,Audi,1395,Petrol,19.2,A3,3510000.0,5,Automatic,35 TFSI Technology
3,Audi,1968,Diesel,15.73,Q3,3653000.0,5,Manual,30 TDI Premium FWD
4,Audi,1968,Diesel,15.73,Q3,3968000.0,5,Automatic,35 TDI quattro Premium Plus

In [41]:
# or else we can use  df['Variant']=df['Variant1'].fillna(df['Variant2'].str.strip())----> 
#bcoz, here in variant2 there is more space.. to remove that we use strip

vv=[]
for i in df['Variant']:
    i=str(i).replace('  ','')
    vv.append(i)

In [42]:
df['Variant']=vv

In [43]:
df.Variant

0              35TDITechnology
1            35TFSIPremiumPlus
2             35TFSITechnology
3              30TDIPremiumFWD
4      35TDIquattroPremiumPlus
5                30TFSIPremium
6          2.0TDIDesignEdition
7             35TDIPremiumPlus
8            30TFSIPremiumPlus
9         30TFSITechnologyPack
10         35TDITechnologyPack
11                      40TFSI
12            35TDIPremiumPlus
13             35TDITechnology
14           45TFSIPremiumPlus
15            45TFSITechnology
16                   Sportback
17                 35TDIMatrix
18                35TFSIMatrix
19                      45TFSI
20                      2.0TDI
21                      60TFSI
22                       50TDI
23                       60TDI
24                         W12
25                   50TDIPlus
26                      D-Lite
27                     D-Lite+
28                        Era+
29                      Magna+
                ...
470             1.5TDIHighline
471        1.5TDIComfortlineAT
472           1.5TDIHighlineAT
473            1.6MPITrendline
474          1.6MPIComfortline
475             1.6MPIHighline
476        1.2TSIComfortlineAT
477           1.2TSIHighlineAT
478        1.5LTDIHighlinePlus
479        1.6LMPIHighlinePlus
480       1.2TSIHighlinePlusAT
481      1.5LTDIHighlinePlusAT
482        SportsEditionDiesel
483        SportsEditionPetrol
484      Comfortline2.0LTDIAMT
485         Highline2.0LTDIAMT
486          2.0TDIComfortline
487             2.0TDIHighline
488             Trendline1L(P)
489           Comfortline1L(P)
490              Highline1L(P)
491           Trendline1.5L(D)
492            Highline1.5L(D)
493         Comfortline1.5L(D)
494               Allstar1L(P)
495             Allstar1.5L(D)
496          HighlinePlus1L(P)
497        HighlinePlus1.5L(D)
498        SportsEditionPetrol
499        SportsEditionDiesel
Name: Variant, Length: 500, dtype: object

0              35TDITechnology
1            35TFSIPremiumPlus
2             35TFSITechnology
3              30TDIPremiumFWD
4      35TDIquattroPremiumPlus
5                30TFSIPremium
6          2.0TDIDesignEdition
7             35TDIPremiumPlus
8            30TFSIPremiumPlus
9         30TFSITechnologyPack
10         35TDITechnologyPack
11                      40TFSI
12            35TDIPremiumPlus
13             35TDITechnology
14           45TFSIPremiumPlus
15            45TFSITechnology
16                   Sportback
17                 35TDIMatrix
18                35TFSIMatrix
19                      45TFSI
20                      2.0TDI
21                      60TFSI
22                       50TDI
23                       60TDI
24                         W12
25                   50TDIPlus
26                      D-Lite
27                     D-Lite+
28                        Era+
29                      Magna+
                ...
470             1.5TDIHighline
471        1.5TDIComfortlineAT
472           1.5TDIHighlineAT
473            1.6MPITrendline
474          1.6MPIComfortline
475             1.6MPIHighline
476        1.2TSIComfortlineAT
477           1.2TSIHighlineAT
478        1.5LTDIHighlinePlus
479        1.6LMPIHighlinePlus
480       1.2TSIHighlinePlusAT
481      1.5LTDIHighlinePlusAT
482        SportsEditionDiesel
483        SportsEditionPetrol
484      Comfortline2.0LTDIAMT
485         Highline2.0LTDIAMT
486          2.0TDIComfortline
487             2.0TDIHighline
488             Trendline1L(P)
489           Comfortline1L(P)
490              Highline1L(P)
491           Trendline1.5L(D)
492            Highline1.5L(D)
493         Comfortline1.5L(D)
494               Allstar1L(P)
495             Allstar1.5L(D)
496          HighlinePlus1L(P)
497        HighlinePlus1.5L(D)
498        SportsEditionPetrol
499        SportsEditionDiesel
Name: Variant, Length: 500, dtype: object